### ISSUE TITLE
Force static linkage

### ISSUE THREAD

**Issue by jjberry314** [tgockel/json-voorhees#119]
Is there a compile option to force static linkage rather than generating a shared object?

Right now, the only way I can see to do it is to edit CMakeLists.txt line 132

**Comment by tgockel** [comment]
Yes -- when you run CMake, add `-DLIBRARY_TYPE=STATIC`. Example:

    $> cmake -DLIBRARY_TYPE=STATIC ..

**Comment by jjberry314** [comment]
Thanks!
