### ISSUE TITLE
What is the inverse of traverse?

### ISSUE THREAD

**Issue by jwaterloo** [tgockel/json-voorhees#43]
Use Case
In web development, upon request, it is common to take a collection of paths and values and reconstruct an entire JSON tree.
In web development, upon response, it is common to take a value and flatten it into a collection of paths and values.

This is performed in PHP and in jQuery which adds to their success. In the case of jQuery this was a breaking change but they did it any way because it was so important. Many [C++] JSON libraries omit this capability.

Your library does have traverse that could be used to turn a json object into a map<jsonv::path, jsonv::value>, though a convenience function to do this common use case would be appreciated. So the former use case is mostly taken care of; except for the preceding "." common to your paths.

Now what about the former use case? What is the inverse of traverse function?
value has the following
value& at_path (const path &p)
but it doesn't seem to have
void set_value_at_path (const path &p, ?value?)
"value & 	path (const path &p)"  comes close but doesn't take an additional ?value? parameter.
For convenience it would be great if there was a batch void paths|set_values_at_paths(std::map<path, value> values). It would be beneficial to perform this to an existing non primitive values or statically to create a new value.

In both use cases strongly type [de]serialization to and from map<path,value> is also welcomed for convenience.

Though at a minimal a set_value_at_path function is needed and all the others could be derived. If this can be performed now, please document how due to the importance of the proliferation of the web and its contribution to the popularity of JSON.

**Comment by tgockel** [comment]
Since `at_path` has a mutable overload, you could say something like this:

   val.at_path(p) = something;

**Comment by tgockel** [comment]
But I do like the idea of having a function `foo` that goes `foo(ForwardIterable<std::pair<path, value>> input) -> value`, my only question would be what to call such a function? `build`?

**Comment by jwaterloo** [comment]
Thank you! Thank you!

**Comment by jwaterloo** [comment]
build, aggregate, implode ... whatever as long as we have it. Please if 
we could have 2 variants. your first that creats object and a second to 
replay on an existing object.

**Comment by tgockel** [comment]
What are the names of the jQuery and PHP functions for this operation? I'd like to maintain some consistency with the rest of the world.

**Comment by jwaterloo** [comment]
jQuery: param()
PHP: $_GET, $_POST, $_REQUEST

There are no real names as they are nearly automatic hidden below the 
api/language framework. Closest name in jQuery is param(). Allow me to 
explain

if form fields are named as the following
person[0][first_name]
person[0][last_name]
person[1][first_name]
person[1][last_name]

then when the form get submitted to a PHP server than the developer 
doesn't have to issue 4 get calls from a map and then somehow have to 
know the structure and recombine the data into a tree. instead the 
developer does one call to $_POST and the data is already there.

To complement this jQuery can use the param function to turn any object 
into a equivalent data as if the field names have accessors. Most jQuery 
AJAX functions can take a single data object and then whatever that 
function internally will call param and do the AJAX call.
see references below for more information


///////////////////////////////////////////////////////////////////


jQuery

http://api.jquery.com/jQuery.param/
jQuery.param()
turns
{
   a: {
     one: 1,
     two: 2,
     three: 3
   },
   b: [ 1, 2, 3 ]
}
into
a[one]=1&a[two]=2&a[three]=3&b[]=1&b[]=2&b[]=3

PHP

http://php.net/manual/en/language.variables.predefined.php
$_GET    = &$HTTP_GET_VARS;
$_POST    = &$HTTP_POST_VARS;
$_ENV    = &$HTTP_ENV_VARS;
$_SERVER  = &$HTTP_SERVER_VARS;
$_COOKIE  = &$HTTP_COOKIE_VARS;
$_REQUEST = array_merge($_GET, $_POST, $_COOKIE);

http://php.net/manual/en/reserved.variables.post.php
<form ....>
<input name="person[0][first_name]" value="john" />
<input name="person[0][last_name]" value="smith" />
...
<input name="person[1][first_name]" value="jane" />
<input name="person[1][last_name]" value="jones" />
</form>

<?php
var_dump($_POST['person']);
//will get you something like:
array (
0 => array('first_name'=>'john','last_name'=>'smith'),
1 => array('first_name'=>'jane','last_name'=>'jones'),
)
?>

http://php.net/manual/en/language.variables.external.php

**Comment by tgockel** [comment]
I believe this is now covered by [`merge` and friends](http://tgockel.github.io/json-voorhees/group__Utility.html#gaf7084b1883a32bab8378bd8aab6ae71f)
