### ISSUE TITLE
Invalid `\uxxxx` in a parsed string throws `range_error`

### ISSUE THREAD

**Issue by sth** [tgockel/json-voorhees#48]
If a json string is parsed and contains a string literal with a `\u` that is not followed by hex digits, a `range_error` is thrown by `from_hex_digit`, but the surrounding code doesn't expect that.

The `parse_string()` function, which calls the string decoding, only handles `decode_error`, not `range_error`. Probably this function should handle `range_error` in the same way, or `string_decode()` should already convert it into a `decode_error` when parsing the `\u` escape.

The exception can for example be triggered by this:

    "\"\\uzzzz\""_json

**Comment by tgockel** [comment]
Agreed -- it makes more sense to have `from_hex_digit` throw a `decode_error` here.

**Comment by tgockel** [comment]
Fixed.
