### ISSUE TITLE
Unresolved External Symbol using MSVC 15 

### ISSUE THREAD

**Issue by IkerGimenez** [tgockel/json-voorhees#57]
I compiled jsonv into libs using the provided solution, and besides looking by default for a dll configuration instead of a static library, the linker is generating:

    jsonv.lib(value.obj) : error LNK2001: unresolved external symbol "int __cdecl jsonv::compare(class jsonv::value const &,class jsonv::value const &)" (?compare@jsonv@@YAHABVvalue@1@0@Z)

I'm only linking with a jsonvd.lib in debug and jsonv.lib in release. What am I doing wrong? This is compiled for x86.

**Comment by tgockel** [comment]
This should work now...unfortunately, I never use Windows, so I can miss this sort of thing.
